### ISSUE TITLE
Pty.js uses 100% CPU

### ISSUE THREAD

**Issue by shockone** [black-screen/black-screen#107]
Steps to reproduce:

* Run `sleep 20` or any other command that doesn't execute immediately.
* Check the CPU usage.

**Comment by mzgnr** [comment]
Its a known bug since  2013 https://github.com/chjj/pty.js/issues/39 , I could not find any PR or commit for this issue.

**Comment by iiegor** [comment]
https://github.com/chjj/pty.js/issues/39#issuecomment-146755794 could fix this.

**Comment by shockone** [comment]
@iiegor, I fixed it in exactly the same way. https://github.com/black-screen/black-screen/blob/master/src/PTY.ts#L13
