### ISSUE TITLE
Show git status in the status line.

### ISSUE THREAD

**Issue by shockone** [black-screen/black-screen#11]

**Comment by midhunkrishna** [comment]
@shockone  can you elaborate a bit? LIke this?
![capture](https://cloud.githubusercontent.com/assets/983675/9704857/cd6755d6-54d1-11e5-977a-d0b2243826b5.JPG)

**Comment by bucaran** [comment]
I think he refers to the status bar at the bottom. The pictures shows a typical powerline which has to do more with the shell than the term emulator.

**Comment by shockone** [comment]
@midhunkrishna, you understood me correctly, looking at the bottom bar I want to know if the branch is clean an all that. I'm not sure if it should be a different colour or something else, though.

**Comment by onbjerg** [comment]
@shockone A different color would do. The Atom editor does this, and it's great. At least, it looks great.
