### ISSUE TITLE
Autocomplete suggestions don't disappear upon returning to beginning of line

### ISSUE THREAD

**Issue by draughoncollin** [black-screen/black-screen#111]
When the user comes back to the start of the line in Black Screen, the Autocomplete suggestions should disappear.
![screen shot 2015-09-09 at 6 27 04 am](https://cloud.githubusercontent.com/assets/6424040/9760576/e48cd006-56bb-11e5-8c2c-7ba56dde27d4.png)

**Comment by G07cha** [comment]
@draughoncollin, thanks for your contribution, I didn't pay attention to this.
