### ISSUE TITLE
Gitter Room?

### ISSUE THREAD

**Issue by N00D13** [black-screen/black-screen#114]
What do you guys think, about a Gitter Chat Room for Questions etc. ?

**Comment by draughoncollin** [comment]
There already is one:
https://gitter.im/black-screen/black-screen?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by joshtoo** [comment]
We already gotter :p

**Comment by N00D13** [comment]
Sorry my fault :smile:
