### ISSUE TITLE
All cd attempts fail

### ISSUE THREAD

**Issue by oompt** [black-screen/black-screen#120]
All ``cd`` fails. 

Here's what I attempted to fix the error. 

### First Try
1. Pulled the latest from the repo
2. Deleted the old app 
3. Re-built the app. <br>
``cd Desktop``         <br>
``cd Desktop/``

Fails. 

### Second Try
1. Updated to latest release of El Capitan (beta 6)
2. Deleted the old app 
3. Re-built the app. <br>
``cd Desktop``         <br>
``cd Desktop/``

Fails.

![blep](http://f.cl.ly/items/463t1d2H2g1t3O3e192E/Image%202015-09-09%20at%202.53.16%20PM.png)

![bleep](http://f.cl.ly/items/0l2v1s3C111b0b2d3a2g/Image%202015-09-09%20at%202.57.06%20PM.png)

![bloop](http://f.cl.ly/items/3m0d0Z2Q1G151Y2L1D2P/Image%202015-09-09%20at%202.56.03%20PM.png)

**Comment by alebcay** [comment]
This is happening for me too.

**Comment by draughoncollin** [comment]
Wasn't able to recreate with the latest pull from base. Are either of you pulling from a branch?

**Comment by G07cha** [comment]
@oompt, @alebcay, can you provide `whereis cd` command output please?

**Comment by alebcay** [comment]
`whereis cd` returns `/usr/bin/cd`.

**Comment by G07cha** [comment]
I've assumed that it could be alias problem but path is correct.

**Comment by G07cha** [comment]
Logs from developer console are clear?

**Comment by oompt** [comment]
![bleep](http://f.cl.ly/items/0y3X0519033S443Z2D13/Image%202015-09-10%20at%2010.30.56%20AM.png)

I'm part of the El Capitan beta test, and they just pushed the official release today, so I'll upgrade to that and see how things look after. @alebcay are you a beta tester too by any chance?

**Comment by oompt** [comment]
``whereis cd``
> /usr/bin/cd

**Comment by oompt** [comment]
Upgraded to El Capitan Golden Master Candidate. Still seeing the same errors.

**Comment by shockone** [comment]
@G07cha `cd` is a built function for Black Screen, we don't use the binary from PATH.

**Comment by shockone** [comment]
@oompt, I assume you're in the home directory and don't rely on `CDPATH`, right?

**Comment by alebcay** [comment]
@oompt, no, I'm on Yosemite 10.10.5.

**Comment by oompt** [comment]
Yes, home directory and no CDPATH that I have defined.  

I am using Prezto, and when I did a seach, I found [this](https://github.com/sorin-ionescu/prezto/search?utf8=%E2%9C%93&q=CDPATH), which might be involved. 

If @alebcay is also on Prezto we might be onto something.

**Comment by shockone** [comment]
That's definitely not prezto, the cd command isn't the one from your system, but this one: https://github.com/black-screen/black-screen/blob/master/src/Command.ts#L6-L6

**Comment by LK** [comment]
I was having the same issue, and I looked into it a bit. I believe the issue is that there's an alias configured for `cd`, which gets expanded before `Command.isBuiltIn` is called. In my case I had `cd='nocorrect cd'` configured, which prevented it from going to the built-in `cd` function.

**Comment by oompt** [comment]
I can confirm this was my problem as well. 

For everyone's edification: you can just add ``unalias cd`` to your .bashrc, .zshrc, etc.

**Comment by shockone** [comment]
@LK, thank you. From now on Black Screen will check if the executable exists before starting the process. 

![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/ue7jj4jl.png)
