### ISSUE TITLE
Uncaught TypeError on key press

### ISSUE THREAD

**Issue by CastleCorp** [black-screen/black-screen#125]
On startup of black-screen using
> npm start

I am getting an Uncaught TypeError whenever I press a key in the black-screen window. 
The following the complete log from startup that is printed to the terminal, with the error showing at the end. 

> black-screen@0.0.1 start /Volumes/Zeus/Documents/github/black-screen
> gulp

>[19:31:23] Requiring external module babel-core/register
>[19:31:24] Using gulpfile /Volumes/Zeus/Documents/github/black-screen/gulpfile.babel.js
>[19:31:24] Starting 'default'...
>[19:31:24] Starting 'watch'...
>[19:31:24] Starting 'clean'...
>[19:31:24] Finished 'clean' after 137 ms
>[19:31:24] Starting 'typescript'...
>[19:31:24] Starting 'sass'...
>[19:31:25] Starting 'react'...
>[19:31:25] Finished 'default' after 1.01 s
>[19:31:27] gulp-notify: [Black Screen Watcher] React has been compiled.
>[19:31:27] Finished 'react' after 2.27 s
>[19:31:34] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
>[19:31:34] Finished 'typescript' after 9.39 s
>[19:31:38] /Volumes/Zeus/Documents/github/black-screen/compiled/all.css reloaded.
>[19:31:38] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
>[19:31:38] Finished 'sass' after 13 s
>[19:31:38] Finished 'watch' after 14 s
>[81821:0910/193139:INFO:renderer_main.cc(200)] Renderer process started
>[81819:0910/193140:INFO:CONSOLE(109)] "Download the React DevTools for a better development >experience: https://fb.me/react-devtools", source: /Volumes/Zeus/Documents/github/black->screen/node_modules/react/lib/React.js (109)
>[81819:0910/193141:INFO:CONSOLE(91)] "Uncaught TypeError: $(...).fixedsticky is not a function", >source: /Volumes/Zeus/Documents/github/black-screen/compiled/views/prompt.js (91)
>[81819:0910/193149:INFO:CONSOLE(105)] "Uncaught TypeError: $(...).caret is not a function", source: >/Volumes/Zeus/Documents/github/black-screen/compiled/views/prompt.js (105)

Anyone else experiencing this? I'm on Yosemite if it matters.

**Comment by shockone** [comment]
@CastleCorp, can you try to reinstall the packages?
```
npm install
```

Please close the issue if it helped.

**Comment by beldar** [comment]
I had to ```bower install``` manually

**Comment by shockone** [comment]
@beldar, doesn't it start for you when you do `npm install`?

**Comment by beldar** [comment]
It didn't no, it actually didn't do it even when I did ```bower install```  I had to create a ```.bowerrc```  file defining the directory to be installed, then it worked, maybe some global configuration I have?

**Comment by CastleCorp** [comment]
@shockone @beldar manual install worked
