### ISSUE TITLE
Git branch label after switching to another branch

### ISSUE THREAD

**Issue by G07cha** [black-screen/black-screen#126]
As you can see after checkout branch still "master".
![screen shot 2015-09-11 at 10 57 06 am](https://cloud.githubusercontent.com/assets/6943514/9809787/f2146400-5873-11e5-83b0-be7f0cce84cc.png)

**Comment by shockone** [comment]
Can't reproduce. Did it work for you before?

**Comment by shockone** [comment]
@G07cha still doesn't work for you?

**Comment by G07cha** [comment]
Yep, still don't working, tried with new empty git repository, same result. Black screen just don't updating label. On `git init` label with master branch don't appear same as on `git checkout` to another branch.

**Comment by shockone** [comment]
@G07cha, you use OS X, right?

**Comment by G07cha** [comment]
OS X 10.10.5 Yosemite

**Comment by shockone** [comment]
I changed a couple of things in this area recently, if it still doesn't work, please reopen the issue.

**Comment by G07cha** [comment]
Still expecting this issue. Possible ways to resolve: get current branch each time(may decrease performance), check command for 'git checkout' existence

**Comment by shockone** [comment]
Well, git checkout changes the content of the file `.git/HEAD`. Does it for you? Is the method [updateGitData](https://github.com/black-screen/black-screen/blob/9aa44894e90b7c3813a33e17b192a2e5528e0ee7/src/Terminal.ts#L103-L103) called when you checkout?

**Comment by G07cha** [comment]
Yes, path is correct but it called only on start or when I switching folders

**Comment by shockone** [comment]
How about this function? Is it called when you checkout another branch? https://github.com/black-screen/black-screen/blob/9aa44894e90b7c3813a33e17b192a2e5528e0ee7/src/Terminal.ts#L94-L94

**Comment by G07cha** [comment]
No it's not.

**Comment by shockone** [comment]
It means that inotify (or how is it called on OS X) doesn't work as expected. Do you remember changing any related system settings?

**Comment by G07cha** [comment]
[Fswatch](https://github.com/emcrisostomo/fswatch) is an alternative of inotify for OS X. I'm don't changing anything related to this manually.
