### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by stanier** [black-screen/black-screen#131]
Not trying to be a nagging nancy, but I think we can all agree that anything to do with terminals should support Linux from the start.

Some official support for Linux would be great or at least documentation on how to ensure it's properly installed as I can't get it to install using the described method on any of my machines.

**Comment by TheAtomicGoose** [comment]
FWIW, it's working for me on Arch Linux just fine.

**Comment by mininao** [comment]
Seems to be working on Ubuntu Gnome 14.04 too

**Comment by stanier** [comment]
I'm having problems installing it, but I think it's just npm being slow.  I'm going to try it again and see if I can figure it out.

Either way, README states that Linux is not officially supported and I feel official support will he helpful in the future.

**Comment by mininao** [comment]
:+1:

**Comment by flawiddsouza** [comment]
Please check before creating your own issue: [Linux support #49 ](https://github.com/black-screen/black-screen/issues/49). There's a lot of info there.

**Comment by stanier** [comment]
@flawiddsouza Thank you, I hadn't found that with a quick search of the issues, but my eyes tend to miss things easily.  Closing issue appropriately.
