### ISSUE TITLE
'!!' support

### ISSUE THREAD

**Issue by saada** [black-screen/black-screen#132]
Sample command
```bash
service apache2 start
# > fail message due to not running as sudo
```
 
Normal Terminal:
```bash
sudo !!
# > success message
```

Black Screen:
```bash
sudo !!
# > Black Screen: command "!!" not found.
```

**Comment by shockone** [comment]
Thank you, @saada. I'm not sure it's the most convenient way to work with the history, though. Since we're innovators here, we could do better. Although, it is widely used, and might be more comfortable for people.

**Comment by rhlKumar** [comment]
@shockone, yes, I use it all the time. Just came to file this issue; found simebidy already found it. I could contribute, if you could point me where to look in code implement it.

**Comment by saada** [comment]
@shockone, this is the default linux shell/bash functionality... Are you planning on reinventing the wheel?

**Comment by shockone** [comment]
@saada, kind of. I'm rewriting a terminal emulator, have you noticed? ;)

**Comment by dharma-guardian** [comment]
It's a unix thing, so applies to OSX as well.
I think innovating does not require to break consistencies.
My recommendation would be to access the `history` in auto completion in reversed order (last command first and so on) by typing `!`.
From the first result, you could just type another `!` or `tab` to select the most recent command or a number, to filter the auto-complete list. 
It would be an addition to the standard behavior, if for example you completely forgot the command you were typing before.

**Comment by woverton** [comment]
Please add this it is ingrained into terminal usage and is very useful.

**Comment by htor** [comment]
> @saada, kind of. I'm rewriting a terminal emulator, have you noticed? ;)

Are you also planning to write your own shell?

**Comment by shockone** [comment]
@htor I would very much like to avoid it, but I wasn't able to make existing shells behave in the way I want.

You're right, guys, we should support history expansion commands.

**Comment by saada** [comment]
@shockone, I agree that we can innovate and find a more clever way to interact with history. But like @dharma-guardian said: "I think innovating does not require to break consistencies.".

**Comment by jerch** [comment]
@shockone Maybe some blackscreen-to-shell translation layer will help to get things sorted. Writing a whole new shell is like - well writing your own OS ;)

Meanwhile it is also possible to call a native shell in blackscreen and use the native stuff there (as long as the keys are mapped correctly it will just work).

**Comment by shockone** [comment]
Now it works, but has some known issues. Most importantly, you can't do `!!` two times in a row. I'll try to deal with it tomorrow.

Check this out:
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/-91kafl3.png)
