### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by KuTi** [black-screen/black-screen#135]
>npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

>npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

https://yadi.sk/i/TdoRvlQ-j6Hxw

**Comment by Voyga** [comment]
tried `sudo`?

**Comment by KuTi** [comment]
@Voyga : I've tried

**Comment by r1cebank** [comment]
It looks like you are using Node v4.0, it could cause unexpected issues with node-gyp. Try to downgrade to v0.12.7

**Comment by RobertoUa** [comment]
Actually it is supposed to work with node v4. Try `rm -rf node_modules && npm install`

**Comment by shockone** [comment]
You can also try to remove the `~/.node-gyp` directory.

**Comment by Yitsushi** [comment]
After I removed gyp and modules directories, the problem disappeared.

`rm -rf ~/.node.gyp && rm -rf node_modules && npm install`

**Comment by KuTi** [comment]
Thanks all,
I deleted ~/.node-gyp,  node_modules and reinstalled successfully. Must have Xcode (make) to build applications

**Comment by KuTi** [comment]
Please close this Issue
