### ISSUE TITLE
Do not add the unknown commands to history

### ISSUE THREAD

**Issue by nounoursheureux** [black-screen/black-screen#137]
I think that if the user enters an unknown command it should not be added to the history, because it will be suggested later and it is annoying to have "wrong" suggestions. What do you think ? :smile:

**Comment by onbjerg** [comment]
If I enter something wrong, I usually go back in the history and just correct it. I think that we could maybe implement some sort of suggestion for wrong commands, much akin Google's "Did you mean xyz?"

**Comment by shockone** [comment]
That's an interesting idea. Ideally we wouldn't allow you to press enter, if the command is unknown. For example, now you can't execute an empty command. It will be pretty easy to implement, but I'm not sure about performance.

**Comment by nounoursheureux** [comment]
> If I enter something wrong, I usually go back in the history and just correct it. I think that we could maybe implement some sort of suggestion for wrong commands, much akin Google's "Did you mean xyz?"

You're right. Ideally I think it should be in the history but not in the suggestions, but I guess this is not really feasible ? 

> That's an interesting idea. Ideally we wouldn't allow you to press enter, if the command is unknown. For example, now you can't execute an empty command. It will be pretty easy to implement, but I'm not sure about performance.

If the performance cost isn't too high I think this would be useful :+1:

**Comment by falsefive** [comment]
The user should always decide what to do with something like that, you
waste too much time trying to fix things like that for the user.

**Comment by shockone** [comment]
I added the idea about not allowing to execute wrong commands. The title of this PR is about a different suggestion, which won't be implemented. Closing it.
