### ISSUE TITLE
Don't use port 35729

### ISSUE THREAD

**Issue by FezVrasta** [black-screen/black-screen#140]
Seems like you are using the port 35729 for black-screen.

This is a common port used on projects based on grunt/node/npm etc so having it busy by black-screen make difficult run these kind of projects directly inside black-window.

```
Fatal error: Port 35729 is already in use by another process.
```

Consider using a different port to prevent collisions.

**Comment by DamonGant** [comment]
Since this is in the freely allocatable range, consider opening this issue at other projects that use this port. This port should always be assumed to be blocked.

**Comment by FezVrasta** [comment]
livereload.js uses that port and is much more famous than your app, I doubt it will change port for you and you will lose all the livereload users

**Comment by DamonGant** [comment]
I am not part of this project, just FYI.

Ports in that range are usable by anybody, so any user should have a sensible fallback.

**Comment by shockone** [comment]
Fixed.
