### ISSUE TITLE
Re-locating cursor will retain position for only one action

### ISSUE THREAD

**Issue by williara** [black-screen/black-screen#141]
After relocation, the cursor will only preserve position for one action (e.g. delete or insert), then repositions to end of line

**Comment by shockone** [comment]
Confirmed.

**Comment by williara** [comment]
Do you have an IRC channel to discuss? I would like to contribute to this project, but it would be nice to get assistance in getting started :)

**Comment by flawiddsouza** [comment]
No IRC but: [![Join the chat at https://gitter.im/shockone/black-screen](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/shockone/black-screen)
