### ISSUE TITLE
Are there any plans to create an "atom.io" plugin from this?

### ISSUE THREAD

**Issue by serapath** [black-screen/black-screen#142]
...or are there plans to add an editor to `black-screen` instead and have a landscape of extensions similar to what `atom` has?

I'm using [atom.io](http://atom.io) for its lovely community and the awesome extensions and features they create. I know a lot of people that would love to use an amazing installable cross-platform terminal.

There are many people who use in-terminal editors ([vim](http://www.vim.org/), [emacs](https://www.gnu.org/software/emacs/), [spacemacs](https://github.com/syl20bnr/spacemacs), [slap](https://github.com/slap-editor/slap) and then use [`tmux`](https://tmux.github.io/), `screen`, `terminator`, and the like and they are able to save the whole session on a project per project basis.

It's great, that for different projects, an editor like `atom` will save your current tabs and panes and restore them the next time, but there is no `terminal tab` yet, that could add several terminals with different terminal titles and `pwd`s and the like to view a particular project.

The one's i know about:
* https://github.com/atom-archive/terminal
* https://github.com/romgrk/termrk
* https://github.com/tjmehta/atom-term
* https://github.com/f/atom-term2
* https://github.com/isis97/atom-terminal-panel
* https://github.com/thedaniel/terminal-panel

**Comment by ruffsl** [comment]
+1

**Comment by flawiddsouza** [comment]
I think you'll find your answer here: https://github.com/black-screen/black-screen/issues/40
