### ISSUE TITLE
Invalid UTF-8

### ISSUE THREAD

**Issue by Nonlimit** [black-screen/black-screen#146]
![invalid-utf-8](https://cloud.githubusercontent.com/assets/11960153/9988902/0fde3b28-605d-11e5-8c45-57bd230e85c6.png)
npm start and this problem on windows 10 :(

**Comment by shockone** [comment]
Hi, Юлічка ;). Currently we don't officially support Windows. It might work, if you're lucky, though.

I'm sorry about that, and promise to support all the major platforms after the 1.0.0 release, but it's just too much hassle right now.
