### ISSUE TITLE
Allow `npm install -g black-screen`

### ISSUE THREAD

**Issue by dbkaplun** [black-screen/black-screen#149]

**Comment by iiegor** [comment]
Why would you want to do that? :confused:

**Comment by flawiddsouza** [comment]
I think he's suggesting something like this: https://www.npmjs.com/package/speed-test

**Comment by shockone** [comment]
I don't think it's a proper distribution model. I'd rather have it installed using GitHub releases or platform package managers.

**Comment by aslafy-z** [comment]
Could you think about fixing package.json file to work with npm github installer (npm install shockone/black-screen -g) ? It could be great and do not use the npm repository :)
