### ISSUE TITLE
Stand alone installer for OSX

### ISSUE THREAD

**Issue by adamatan** [black-screen/black-screen#151]
Hi,

Is there a stand-alone installer for OSX, please? 

Thanks in advance,
Adam

**Comment by JamesMD** [comment]
@adamatan, execute `npm run package` inside your cloned repo, which will create a standalone app. Once finished, it will create a `Black Screen-darwin-x64` folder which holds `Black Screen.app` in your `Application` folder.

**Comment by adamatan** [comment]
Thanks a lot for the answer, will do.
Do you think it would make sense to make the app file publicly downloadable without git-cloning and compiling?

**Comment by nblackburn** [comment]
@adamatan I think it makes sense once the application is out of beta to use the releases function which ties into the issue #145.

**Comment by JamesMD** [comment]
@adamatan, sorry for the late reply - In a sense, I'd rather it be compiled from binary/source by default as there is no version control in the software itself. If a newer version came out, you'd have to download the app again. Once it's out of beta, I'd probably hope that there is an update functionality from the app itself. Hope this helps. :smiley:

**Comment by shockone** [comment]
Covered by https://github.com/black-screen/black-screen/issues/77.
