### ISSUE TITLE
npm run fails on OS X EI Capitan

### ISSUE THREAD

**Issue by smaty1** [black-screen/black-screen#155]
bogon:black-screen baidu$ npm run
Lifecycle scripts included in black-screen:
  preinstall
    npm prune
  postinstall
    bower prune; bower install; electron-rebuild
  start
    gulp
  test
    gulp typescript; gulp compile-tests; electron run-tests.js

available via `npm run-script`:
  package
    electron-packager . 'Black Screen' --overwrite --platform=darwin --arch=x64 --version='0.31.2' --out='/Applications' --icon='./icon.icns'
bogon:black-screen baidu$

**Comment by shockone** [comment]
What's the expected action? Maybe you confused it with `npm start`?
