### ISSUE TITLE
Piping to an unknown command hangs the terminal

### ISSUE THREAD

**Issue by raboof** [black-screen/black-screen#156]
When I give a command containing a pipe to an unknown command, I don't get my prompt back:

![selection_040](https://cloud.githubusercontent.com/assets/131856/10418505/060f4b90-705d-11e5-8850-a208aa58fe7a.png)

**Comment by shockone** [comment]
Thank you for the report, @raboof.

**Comment by raboof** [comment]
No problem, thanks even more for the fix!
