### ISSUE TITLE
Can't close window with keyboard shortcut on Linux

### ISSUE THREAD

**Issue by raboof** [black-screen/black-screen#157]
In the console:
```
[27575:1013/224706:INFO:CONSOLE(71)] "Uncaught TypeError: Cannot read property 'slice' of undefined", source: /home/aengelen/dev/black-screen/node_modules/rx/dist/rx.js (71)
```

This is with rx 3.1.2

**Comment by shockone** [comment]
Ctrl-w should delete the word at caret, as it is in other shells. `TypeError` isn't expected behaviour either, but it shouldn't close the window. Use Cmd+w instead.

**Comment by raboof** [comment]
Ah, good point. I'm on Linux, and when I open the 'File' menu it does list 'Ctrl-W' as shortcut for closing the window. Indeed that probably isn't right as it clashes with using Ctrl-W for removing the last word.

**Comment by raboof** [comment]
(I can no longer seem to reproduce the TypeError)

**Comment by shockone** [comment]
Strangely, there is no File menu for OS X at all. Removed it for Linux as well.
