### ISSUE TITLE
Black Screen opens in expanded view every time the app is closed and re-opened

### ISSUE THREAD

**Issue by jdsimcoe** [black-screen/black-screen#163]
@shockone Every time I close and re-open Black Screen the window fills my entire screen:

![k6lgzwk5ysbelsc_ovsnofvj94wvt2v_meliivkguhk](https://cloud.githubusercontent.com/assets/275617/10526732/677f51ae-7341-11e5-8ed5-71ef54d2c3f3.png)

Is there a way to keep this from happening and remember the width I last had the window at?

**Comment by shockone** [comment]
There is, and one time it was kind of restoring size (and position), but there were some bugs. I tried to fix it, but after a while decided to delay this feature. It's definitely going to be implemented.

**Comment by jdsimcoe** [comment]
:+1:
