### ISSUE TITLE
Black Screen Website

### ISSUE THREAD

**Issue by al0p** [black-screen/black-screen#168]
I was thinking it would be cool Black Screen have a website and thought in an initial concept .
What do you guys think ?

![blackscreen](https://cloud.githubusercontent.com/assets/997620/10682644/f4228f24-7916-11e5-9eb8-d9743c1e59b6.png)

**Comment by nblackburn** [comment]
Looks good but have a couple suggestions.

- Add a background to the header banner (_a bit bland on it's own_).
- Change the button style to the chevron style used in BS.

**Comment by pmros** [comment]
:cool:

**Comment by RobertoUa** [comment]
Whoa, nice! I love it!

**Comment by iiegor** [comment]
:+1:

**Comment by Voyga** [comment]
Look really good.

**Comment by jaoued** [comment]
:+1:

**Comment by shockone** [comment]
Hi, @al0p. Thank you for the initiative; I like your style. However, I must disappoint you: we'd like to avoid having a web-site for now because it requires additional time for support and updates. May I contact you in the future, when we release a stable version?

**Comment by mzgnr** [comment]
Sorry for being late! @shockone I've found a full time job and ready to maintain website! I started working on logo and structuring website. I'm really sorry for being late, I could not focus on this without a regular job.

**Comment by Swizz540** [comment]
I think you might be considere to use [GitHub Pages](https://pages.github.com/).

How is presented, this website do not required many updates.

Create the [black-screen.github.io](https://github.com/black-screen/black-screen.github.io) repo, and let them work on it :wink:

**Comment by pmros** [comment]
@Swizz540, I'm agree with. Black Screen Website should be a simple front-end in order to popularize this project. It requires little maintenance.

**Comment by al0p** [comment]
Hi Guys, sorry the delay to reply.

@shockone Thank you. I'm here for any kind of help you need with the project. :)

**Comment by lenovouser** [comment]
Why did you close this?

**Comment by iiegor** [comment]
@lenovouser see https://github.com/black-screen/black-screen/issues/168#issuecomment-150920677

**Comment by lenovouser** [comment]
Ah, okay. Sorry for the comment :smile:

**Comment by frenchie4111** [comment]
I know this is closed but: I would be willing to throw together this website, it wouldn't take more than 30 minutes, and as long as we keep the content low it would require very little maintenance. (And github pages is free)
