### ISSUE TITLE
Node-gyp rebuild problem, gyp not installed.

### ISSUE THREAD

**Issue by SurfaceThought** [black-screen/black-screen#174]
Hello! 

First off, I am running linux which I know is not officially supported so please feel free to tell me to gtfo.

So, when trying to install black-screen using npm install, I received the exact same error message that the user was experiencing in this thread:

https://github.com/black-screen/black-screen/issues/147

However, I do no have gyp installed, so I cannot remove it and it is probably not the culprit....

Let me know if you have any suggestions! Thanks! You guys are doing good work.

**Comment by shockone** [comment]
Sorry, @SurfaceThought, I'll close it for the reason you mentioned. I have very limited free time, and I just can't afford to support all platforms right now. If you find a solution, please post it here.
