### ISSUE TITLE
app showing a white screen with a '1' 

### ISSUE THREAD

**Issue by luizkowalski** [black-screen/black-screen#32]
I cloned the project, ran `npm run install-all` and `npm run package` and after install the app, this is what I see

![screen shot 2015-09-06 at 12 59 35](https://cloud.githubusercontent.com/assets/112706/9704027/28963688-5497-11e5-842a-c24d3e2126df.png)

I'm running OSX Yosemite 10.10.5 with npm 2.12.1

**Comment by wikiziner** [comment]
+1

**Comment by jjoos** [comment]
Just had the same issue, you need to start it by running gulp from the project directory (`npm install gulp -g` if you haven't got it installed).

**Comment by kblanks** [comment]
@jjoos That does work but it'd be nice to have a packaged application that can run by itself.

**Comment by shockone** [comment]
Could you guys open the developer tools (cmd+shift+i) and tell me the error in the JavaScript console?

**Comment by luizkowalski** [comment]
well, I reinstalled the app with `npm run package` and worked
computers...

**Comment by umpc** [comment]
![screen shot 2015-09-06 at 6 14 25 pm](https://cloud.githubusercontent.com/assets/5883661/9706902/2d9fa754-54c4-11e5-8714-02f99fe49133.png)

I got it working with the steps posted above.

**Comment by kblanks** [comment]
![JavaScript console on Black Screen](https://i.imgur.com/9d808xV.png)

OS X 10.10.3

**Comment by chrise86** [comment]
I'm still getting this, again OSX 10.10.5, when building the package

**Comment by G07cha** [comment]
Temporary workaround:
1. Open repository's folder
2. Run `gulp` command
3. Copy `all.css` from `compiled` and `main.js` from `compiled/views` to `/Applicatons/Black Screen-darwin-x64/Black Screen.app/Contents/Resurces/app/compiled`

Ping me if this doesn't solve a problem.

**Comment by mzgnr** [comment]
I've found the work around. nom run package does not create compiled folder.
1) npm run install-all
2) npm start
3) Exit from the application and terminate the process
4) npm run package

**Comment by chrise86** [comment]
Thanks guys,@mzgnr's solution worked for me!

**Comment by jbaskeen** [comment]
:+1: 

The README should be updated or the build process needs to handle running gulp
