### ISSUE TITLE
What is the shell used in this term emulator?

### ISSUE THREAD

**Issue by bucaran** [black-screen/black-screen#33]
Beautiful project. I was wondering whether this emulator will let me use my preferred shell (fish) or if it comes with its own builtin shell?

**Comment by mackenza** [comment]
the `package.json` says https://github.com/Gottox/child_pty

**Comment by bucaran** [comment]
@mackenza Thanks. So, the answer is yes?

**Comment by mackenza** [comment]
sorry, I guess my answer wasn't really what you were asking. I am new to the code base, but is it zsh that is being used? You can certainly experiment with the fish shell as you have above. It may work.

**Comment by bucaran** [comment]
@mackenza Yes, that's what I assumed.

I didn't read this anywhere in the README, but I am guessing this term could potentially support video playback, vector/raster graphics.
