### ISSUE TITLE
cannot type or issue commands in vi/vim

### ISSUE THREAD

**Issue by mackenza** [black-screen/black-screen#34]
if I say `vi package.json` or some other file, the vi window comes up in BS but I cannot issue any commands or type.

**Comment by nemesiscodex** [comment]
I manage to write something by pressing `a` and save it with `shift+zz`, but no commands, are key bindings overlapped or ignored? If I press `ctrl` in insert mode I get this character typed in `¢`

**Comment by jaoued** [comment]
+1

**Comment by shockone** [comment]
Now it should work.
