### ISSUE TITLE
Selecting different command in dropdown list

### ISSUE THREAD

**Issue by G07cha** [black-screen/black-screen#46]
Steps to reproduce
1. `mkdir testfolder`
2. `rm -r testfolder`
3. Start typing `rm -r testfolder`
4. Select `mkdir testfolder` from dropdown list by hitting Enter key

*Actual Result:* rm: formated: No such file or directory
*Expected Result:* Create folder

OS X: 10.10.5
Commit: cf8880202fa968b77c631076c215f2ea11ee66bc

**Comment by G07cha** [comment]
UPD: Actually command appending by pressing Enter key don't work at all, is it expecting behavior?

**Comment by shockone** [comment]
It is. At first enter did autocomplete commands. However, there were cases when the autocompletion box was shown, but you wanted to execute what you currently have in the input. So, you had to press escape to hide the popup and then enter, which was very confusing. Now autocompletion works only by pressing the tab key.

**Comment by G07cha** [comment]
In zsh and most of IDE Enter key is applying selected item from dropdown list, ESC key is dismissing dropdown list so if it possible I would like to hear opinion of others users/developers.

**Comment by shockone** [comment]
Reopening to get more feedback. Thank you, @G07cha.

**Comment by shockone** [comment]
No feedback. Closing.
