### ISSUE TITLE
`npm run package` should build for all the platforms

### ISSUE THREAD

**Issue by shockone** [black-screen/black-screen#57]
Currently the package script
```
rm -rf '/Applications/Black Screen.app'; electron-packager . 'Black Screen' --platform=darwin --arch=x64 --version='0.30.0' --out='/Applications' --icon='./icon.icns'
```
is very platform dependent.

Perhaps, it's worth looking into how Atom or other Electron projects are being packaged.

**Comment by G07cha** [comment]
We can use gulp-if for this or just create separate scripts for Unix and non-Unix system

**Comment by shockone** [comment]
https://github.com/maxogden/electron-packager supports builds for different platforms out of the box. Maybe there are better tools.

**Comment by G07cha** [comment]
For production build we can use 'all' for platform and arch options, and for development provide specific scripts.

**Comment by shockone** [comment]
Let's try that.

**Comment by joshtoo** [comment]
@shockone @G07cha - This
