### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by mzgnr** [black-screen/black-screen#62]
It might not be important but I created something like this.

https://www.dropbox.com/s/z33yfpxf4ppdzvo/icon_512x512%402x.png?dl=0

**Comment by G07cha** [comment]
:+1:
I think you should create pull request for this.

**Comment by shockone** [comment]
@mzgnr are you kidding me? It is very important, and I like it! I agree with @G07cha, please create a pull request and also please make an `icns` icon, if you have time. Otherwise, I'll do that. Thank you for the contribution.

**Comment by mzgnr** [comment]
@shockone I'm glad you like it. I'll work on it and create a pull request today :)

**Comment by mzgnr** [comment]
New icon design : https://www.dropbox.com/s/9budqtze1b4bqh7/blackscreen2.png?dl=0

first one or this one ? Do you have any suggestions ?

**Comment by G07cha** [comment]
I like the second.

**Comment by mzgnr** [comment]
I like it more too. I'm focusing on it then.

**Comment by shockone** [comment]
This article might be useful. https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html#//apple_ref/doc/uid/20000957-CH87-SW1

**Comment by shockone** [comment]
I like the second one more. A suggestion: even though the prompt is in the middle, visually it appears closer to the left due to the lighter right side.

**Comment by mzgnr** [comment]
@shockone I'm trying to fix that issue.

**Comment by mzgnr** [comment]
How about now ? https://www.dropbox.com/s/6azzqev4ksi7pl9/test2.png?dl=0 I think its better.

**Comment by G07cha** [comment]
Much better, update pull request

**Comment by G07cha** [comment]
Fixed in #69

**Comment by G07cha** [comment]
Should we also update organization logo?

**Comment by shockone** [comment]
@G07cha, I'll update it in the evening.

**Comment by mzgnr** [comment]
I don't know what is the best resolution for the logo. But here it is https://www.dropbox.com/s/kulm3v43srefor7/github-logo.png?dl=0

**Comment by mzgnr** [comment]
Don't miss my last comment :smile:

**Comment by shockone** [comment]
I won't. Thanks.

**Comment by mzgnr** [comment]
I'm reopening issue because, organisations profile picture has not been updated yet.

**Comment by G07cha** [comment]
Thanks for attention to this, @mzgnr.

**Comment by shockone** [comment]
@mzgnr, sorry about that. Updated.
