### ISSUE TITLE
Custom aliases are not recognized and ctrl + c does not cancel the current line

### ISSUE THREAD

**Issue by RoySegall** [black-screen/black-screen#66]
Hi there. I loved this terminal and i found out two things that are missing:
1. Custom aliases are not recognised
2. When start typing and i want to break the current line i'm typing in the normal terminal ctrl + c and then the line is cleared. In this one it's missing.

**Comment by shockone** [comment]
Hey, @RoySegall. You're using BASH, right? We have aliases import from ZSH now, but we'll surely add BASH in the future. 

I can confirm that Ctrl+C doesn't work as expected. You can type Ctrl+L for now, though. It will clear your screen including the current prompt.

**Comment by mwsteb** [comment]
I'm using zsh but my aliases (in `~/.zshrc`) aren't imported automatically. `source ~/.zshrc` won't work, as apparently, there's no `source` command yet.  Please advise.

**Comment by RoySegall** [comment]
Well... This could be essence of this problem.

**Comment by jdsimcoe** [comment]
`Ctrl+L` still doesn't clear the screen when I'm running a gulp task. Any thoughts?
