### ISSUE TITLE
Can't interrupt actions with ctrl + c

### ISSUE THREAD

**Issue by N00D13** [black-screen/black-screen#68]
For an example, when i ping my loopback and want to kill the action, i want to key interrupt this actions with ctrl + c but nothing happens.

**Comment by G07cha** [comment]
Thanks for contribution, but this is relates to the #66 
We would be grateful to you @N00D13 and @RoySegall if you help us add this feature.

**Comment by shockone** [comment]
I guess the other issue is different: it says that one should be able to clear the prompt from a *not started* command hitting ctrl + c. Reopening.

**Comment by G07cha** [comment]
Oh, my apologies, I misunderstood.

**Comment by joshtoo** [comment]
Sorry, Click Fail

To add to what @N00D13 is running into. For something like "top or iostat" ctl +q will get you out of it, this is not the case with the ping command.

All that being said, some of the standard keyboard shortcuts people are accustomed to when working within a shell should really be consistent. Terminating a process should be assigned to "Ctl + c" / "cmd + c" as an experienced command line user would expect.

**Comment by RoySegall** [comment]
Also if ctrl + q close the window then this will affect people when they will try to exit the git scroller(similar to git log)

**Comment by shockone** [comment]
@RoySegall, duly noted.

**Comment by jdsimcoe** [comment]
@shockone I know there is a referenced #143 which references #66 and #68 but `Ctrl + C` still doesn't kill a process for me when using Black Screen. Any plans on adding support for this?

**Comment by shockone** [comment]
@jdsimcoe, done. Although, I must send a different signal: SIGTERM instead of SIGINT because of an `pty.js` issue. It still stops a command execution, which is what you usually want. It might have weird consequences, though.

**Comment by shockone** [comment]
By the way, interrupted commands have a special icon.
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/y6lte23z.png)

**Comment by jdsimcoe** [comment]
@shockone Nice!

**Comment by RoySegall** [comment]
I would like to re open it - ctl+c suppose not only to stop the current process but also start a new line. Try this in normal terminal and see what happens.

**Comment by shockone** [comment]
@RoySegall, do you mean that when there is no running command it should behave as if you pressed 'return' and just re-draw the prompt?

**Comment by RoySegall** [comment]
In deed. it's suppose to create a new line and clear the old one. To me, for example, it's help to order my thoughts before typing my new command in the cli.

**Comment by shockone** [comment]
@RoySegall, thank you, I'll make it clear the current input, but I won't allow it to create a new prompt. Sorry, you'll have to find a new way to order your thoughts unless you know another reason to have it besides a compulsive behaviour. :)

**Comment by RoySegall** [comment]
The ctrl+c doesn't create a new prompt. It's just create a new row.

**Comment by shockone** [comment]
When I click it repeatedly, I see the following, do you observe a different behaviour?
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/112oqhdg.png)

**Comment by RoySegall** [comment]
This is exactly what is suppose to do but I don't get it. I cloned today the project so have the latest version.

**Comment by shockone** [comment]
Yeah, my screenshot is in iTerm2 and ZSH. But it does display prompts at new lines, doesn't it? Anyway, I'd like to avoid creating empty lines; currently it's impossible to execute an empty command and we plan to disallow execution of incorrect commands.

**Comment by shockone** [comment]
Fixed.
