### ISSUE TITLE
Shaking terminal

### ISSUE THREAD

**Issue by G07cha** [black-screen/black-screen#71]
Steps to reproduce:
1. Fill terminal screen with random commands(`ls` for example)
2. On the end execute some commands that don't have an output(`cd` for example)

*AR:* Terminal start shaking when you typing

[Proof](https://vimeo.com/138594816)

**Comment by mzgnr** [comment]
Terminal is also shaking while scrolling down when cursor is at the bottom of the frame

**Comment by nmn** [comment]
I have the same problem, but I have some more information that should help solve the issue.

The commands in black-screen have position-sticky behavior. That is, when you scroll, the last command sticks to the top of the page. However, chrome doesn't support position: sticky, and so nor does electron. As a result, black-screen is using a javascript workaround, that clearly is root of the shaking problem.

I'll take a crack at solving the issue.

**Comment by jacob-israel-turner** [comment]
I'm getting this problem as well.

**Comment by shockone** [comment]
Fixed.
