### ISSUE TITLE
Font Awesome Doesn't Work After Update to 4.4.0

### ISSUE THREAD

**Issue by shockone** [black-screen/black-screen#95]
Steps to reproduce:

* Change the `font-awesome` version in `package.json` to `4.4.0`.
* `npm install`
* `npm run`
* Execute any command.

Now the arrow up icon, which is usually displayed at the right side of the prompt doesn't show up.
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/hy091tfc.png)

Feel free to work on this task, if you'd like to help the project.

**Comment by mzgnr** [comment]
It is really weird. I'm trying to fix it.

**Comment by mzgnr** [comment]
I think there is a problem in version 4.4.0 with font size and with some other crazy css stuff. I was able to take that screenshot. I'll dive in tomorrow.
![screen shot 2015-09-09 at 01 12 53](https://cloud.githubusercontent.com/assets/6003317/9748858/96ce5112-5690-11e5-89e0-97cf681efde7.png)

**Comment by mzgnr** [comment]
@shockone add this at the bottom of the main.scss. this solves the issue.

.fa {
  transform: translate(0, 0);
}

**Comment by shockone** [comment]
@mzgnr, it worked. Good job!
